# Generated by Django 5.2.8 on 2025-11-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('province', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicianrecord',
            name='politician',
        ),
        migrations.RemoveField(
            model_name='politicianrecord',
            name='province',
        ),
        migrations.RemoveField(
            model_name='politicianrecord',
            name='region',
        ),
        migrations.RemoveField(
            model_name='province',
            name='region',
        ),
        migrations.DeleteModel(
            name='Politician',
        ),
        migrations.DeleteModel(
            name='PoliticianRecord',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
