# Generated by Django 5.2.7 on 2025-11-30 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicians.region')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticianRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('COUNCILOR', 'COUNCILOR'), ('PROVINCIAL BOARD MEMBER', 'PROVINCIAL BOARD MEMBER'), ('VICE MAYOR', 'VICE MAYOR'), ('VICE GOVERNOR', 'VICE GOVERNOR'), ('MAYOR', 'MAYOR'), ('MEMBER, HOUSE OF REPRESENTATIVES', 'MEMBER, HOUSE OF REPRESENTATIVES'), ('GOVERNOR', 'GOVERNOR')], max_length=100)),
                ('party', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(choices=[(2022, 2022), (2006, 2006), (2018, 2018), (2002, 2002), (2010, 2010), (2014, 2014)])),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politicians.politician')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='politicians.province')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='politicians.region')),
            ],
        ),
    ]
