# Generated by Django 5.2.7 on 2025-11-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianrecord',
            name='year',
            field=models.IntegerField(choices=[(2022, 2022), (2019, 2019), (2013, 2013), (2004, 2004), (2010, 2010), (2016, 2016), (2007, 2007)]),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('REGION I', 'REGION I'), ('REGION II', 'REGION II'), ('REGION III', 'REGION III'), ('REGION IV-A', 'REGION IV-A'), ('REGION V', 'REGION V'), ('REGION VI', 'REGION VI'), ('REGION VII', 'REGION VII'), ('REGION VIII', 'REGION VIII'), ('REGION IX', 'REGION IX'), ('REGION X', 'REGION X'), ('REGION XI', 'REGION XI'), ('REGION XII', 'REGION XII'), ('NATIONAL CAPITAL REGION', 'NATIONAL CAPITAL REGION'), ('CORDILLERA ADMINISTRATIVE REGION', 'CORDILLERA ADMINISTRATIVE REGION'), ('REGION XIII', 'REGION XIII'), ('MIMAROPA', 'MIMAROPA'), ('AUTONOMOUS REGION IN MUSLIM MINDANAO', 'AUTONOMOUS REGION IN MUSLIM MINDANAO')], max_length=100, unique=True),
        ),
    ]
