# Generated by Django 5.2.8 on 2025-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_alter_politicianrecord_year_alter_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
