# Generated by Django 5.2.7 on 2025-11-30 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_alter_politicianrecord_year_alter_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianrecord',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='politicians.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
