# Generated by Django 5.2.8 on 2025-11-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0003_alter_politicianrecord_region_alter_region_name'),
        ('politicians', '0003_alter_region_name'),
    ]

    operations = [
    ]
