# Generated by Django 5.2.7 on 2025-11-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0004_merge_20251130_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicianrecord',
            name='community',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
