# Generated by Django 5.2.7 on 2025-12-01 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0005_politicianrecord_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politicianrecord',
            options={'ordering': ['year']},
        ),
    ]
