# Generated by Django 5.2.7 on 2025-12-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0006_alter_politicianrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianrecord',
            name='year',
            field=models.IntegerField(choices=[(2004, 2004), (2007, 2007), (2010, 2010), (2013, 2013), (2016, 2016), (2019, 2019), (2022, 2022)]),
        ),
    ]
