# Generated by Django 5.2.7 on 2025-12-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0007_alter_politicianrecord_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='slug',
            field=models.SlugField(default='default_slug', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
