# Generated by Django 4.2.26 on 2025-12-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("politicians", "0008_politician_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="politicianrecord",
            options={},
        ),
    ]
